### PR TITLE
feat-sar-6308: adjusted bot.py to look for sonraiSwimlane tag and opt…

### PR DESCRIPTION
**Pull request by sonrai-mj**
…ional to look for sonraiCollector tag on AWS accounts

### CODE REVIEW

**Review by sonrai-dwightery — APPROVED** [review]

**Comment by sonrai-dwightery** [comment]
looks good from my side, but i didn't test it.  merging.

**Review by sonrai-dwightery — APPROVED** [review]

**Review by sonrai-dwightery — APPROVED** [review]
looks good.

**Review by sonrai-dwightery — APPROVED** [review]

**Comment by sonrai-dwightery** [comment]
@sonrai-mj  - not sure why after I approve, its' saying review required...

**Comment by sonrai-dwightery** [comment]
@sonrai-mj  - ah, i don't have write access to the sonrai-bots repo. We'll need to get someone with write privs to approve.

**Comment by sonrai-mj** [comment]
@sonrai-dwightery That is what I figured.  Once this merges when we need someone with permissions to update the `remediation-bots` repo too which is what pulls in the changes to this repo into the core code.

**Review by sonrai-bradpe — APPROVED** [review]

**Pull request merged**
